#!/bin/sh
set -e

# Automatically added by dh_python3
if which py3compile >/dev/null 2>&1; then
	py3compile -p pyqtmenu 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p pyqtmenu  || true
fi

if which py3compile >/dev/null 2>&1; then
	py3compile -p pyqtmenu /usr/share/pyqtmenu
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p pyqtmenu /usr/share/pyqtmenu || true
fi

# End automatically added section
