# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayoutManagerWidget(object):
    def setupUi(self, LayoutManagerWidget):
        LayoutManagerWidget.setObjectName("LayoutManagerWidget")
        LayoutManagerWidget.setWindowModality(QtCore.Qt.WindowModal)
        LayoutManagerWidget.resize(581, 419)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LayoutManagerWidget.sizePolicy().hasHeightForWidth())
        LayoutManagerWidget.setSizePolicy(sizePolicy)
        LayoutManagerWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        LayoutManagerWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridLayout_2 = QtWidgets.QGridLayout(LayoutManagerWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.leftlistWidget = QtWidgets.QListWidget(LayoutManagerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftlistWidget.sizePolicy().hasHeightForWidth())
        self.leftlistWidget.setSizePolicy(sizePolicy)
        self.leftlistWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftlistWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.leftlistWidget.setMidLineWidth(0)
        self.leftlistWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.leftlistWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.leftlistWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.leftlistWidget.setObjectName("leftlistWidget")
        self.gridLayout_2.addWidget(self.leftlistWidget, 0, 0, 7, 1)
        self.moveleftBtn = QtWidgets.QPushButton(LayoutManagerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveleftBtn.sizePolicy().hasHeightForWidth())
        self.moveleftBtn.setSizePolicy(sizePolicy)
        self.moveleftBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.moveleftBtn.setObjectName("moveleftBtn")
        self.gridLayout_2.addWidget(self.moveleftBtn, 2, 1, 1, 1)
        self.rightlistWidget = QtWidgets.QListWidget(LayoutManagerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightlistWidget.sizePolicy().hasHeightForWidth())
        self.rightlistWidget.setSizePolicy(sizePolicy)
        self.rightlistWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rightlistWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightlistWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rightlistWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightlistWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.rightlistWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.rightlistWidget.setObjectName("rightlistWidget")
        self.gridLayout_2.addWidget(self.rightlistWidget, 0, 2, 7, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.moverightBtn = QtWidgets.QPushButton(LayoutManagerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moverightBtn.sizePolicy().hasHeightForWidth())
        self.moverightBtn.setSizePolicy(sizePolicy)
        self.moverightBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.moverightBtn.setObjectName("moverightBtn")
        self.gridLayout_2.addWidget(self.moverightBtn, 3, 1, 1, 1)

        self.retranslateUi(LayoutManagerWidget)
        QtCore.QMetaObject.connectSlotsByName(LayoutManagerWidget)

    def retranslateUi(self, LayoutManagerWidget):
        _translate = QtCore.QCoreApplication.translate
        LayoutManagerWidget.setWindowTitle(_translate("LayoutManagerWidget", "Form"))
        self.moveleftBtn.setText(_translate("LayoutManagerWidget", "<"))
        self.moverightBtn.setText(_translate("LayoutManagerWidget", ">"))
