#!/bin/bash

mkdir "raw_to_delete"
for file in *.ARW; do
    
    f="${file%.*}.JPG"

    if [ -f "$f" ]; then 
        echo "1" 
    else
        echo "0"
        $(mv $file "raw_to_delete/$file")
    fi
done
