#!/usr/bin/python3

"""
Python numpy calculator imbed in a rofi interface (python-rofi):
        - can evaluate all numpy expression
        - create a variable containing your result_lists for further usage
"""

from app.rofi_python_calculator import main

if __name__ == '__main__':
    main()
