#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
@Author=Daguhh
"""

import sys

from app.qrcopy import Example
from PyQt5.QtWidgets import QApplication

if __name__ == '__main__':

    app = QApplication(sys.argv)
    ex = Example()
    sys.exit(app.exec_())
