# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayoutManagerWidget(object):
    def setupUi(self, LayoutManagerWidget):
        LayoutManagerWidget.setObjectName("LayoutManagerWidget")
        LayoutManagerWidget.resize(400, 300)
        self.horizontalFrame = QtWidgets.QFrame(LayoutManagerWidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(-1, -1, 401, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftlistWidget = QtWidgets.QListWidget(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftlistWidget.sizePolicy().hasHeightForWidth())
        self.leftlistWidget.setSizePolicy(sizePolicy)
        self.leftlistWidget.setObjectName("leftlistWidget")
        self.horizontalLayout.addWidget(self.leftlistWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.moveleftBtn = QtWidgets.QPushButton(self.horizontalFrame)
        self.moveleftBtn.setObjectName("moveleftBtn")
        self.verticalLayout.addWidget(self.moveleftBtn)
        self.moverightBtn = QtWidgets.QPushButton(self.horizontalFrame)
        self.moverightBtn.setObjectName("moverightBtn")
        self.verticalLayout.addWidget(self.moverightBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.rightlistWidget = QtWidgets.QListWidget(self.horizontalFrame)
        self.rightlistWidget.setObjectName("rightlistWidget")
        self.horizontalLayout.addWidget(self.rightlistWidget)

        self.retranslateUi(LayoutManagerWidget)
        QtCore.QMetaObject.connectSlotsByName(LayoutManagerWidget)

    def retranslateUi(self, LayoutManagerWidget):
        _translate = QtCore.QCoreApplication.translate
        LayoutManagerWidget.setWindowTitle(_translate("LayoutManagerWidget", "Form"))
        self.moveleftBtn.setText(_translate("LayoutManagerWidget", "<"))
        self.moverightBtn.setText(_translate("LayoutManagerWidget", ">"))
